### ISSUE TITLE
can't search images

### ISSUE THREAD

**Issue by diyarit** [ishare2-org/ishare2-cli#14]
Hello guys, 

I'm currently facing this issue can I get some help please.

root@pnetlab:~# ishare search palo
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>

Traceback (most recent call last):
  File "ishare.py", line 118, in <module>
  File "ishare.py", line 112, in main
  File "ishare.py", line 82, in search
TypeError: 'bool' object has no attribute '__getitem__'
[24490] Failed to execute script ishare

Thank you.

**Comment by diyarit** [comment]
The issue was fixed by upgrading the PNET.


thank you guys
